// src/features.js
const features = [
  "Fitur login dengan 2 langkah (password + OTP email), OTP hanya berlaku 2 menit dan maksimal 3 kali salah.",
  "Login gagal 5 kali berturut-turut akan mengunci akun selama 15 menit. Uji fungsional dan batas.",
  "Form registrasi dengan validasi: email harus unik, username min. 6 karakter tanpa spasi, password harus ada simbol.",
  "Sistem reset password via email, tautan berlaku 10 menit dan hanya bisa diklik 1 kali.",
  "Fitur CAPTCHA muncul hanya setelah 3 kali login gagal berturut-turut.",
  "Fitur diskon otomatis 15% hanya berlaku jika total belanja > Rp250.000 dan minimal 2 item berbeda.",
  "Ongkos kirim gratis jika alamat pengiriman dalam radius 5 km dari titik gudang.",
  "Checkout hanya berhasil jika stok semua barang tersedia dan metode pembayaran dipilih.",
  "Form pembayaran dengan validasi kartu kredit: panjang harus 16 digit, format Luhn, tanggal kadaluarsa valid.",
  "Poin loyalitas dikonversi otomatis ke diskon jika > 100 poin, dan tidak bisa digabung dengan voucher.",
  "Perhitungan pajak otomatis: 10% jika pendapatan > Rp50 juta per bulan, bebas pajak jika < Rp5 juta.",
  "Validasi pengeluaran bulanan tidak boleh melebihi saldo bulanan setelah dikurangi tagihan tetap.",
  "Laporan keuangan otomatis mendeteksi jika ada dua transaksi di tanggal sama dengan nominal identik.",
  "Sistem split bill membagi pembayaran berdasarkan jumlah orang, tapi minimum tagihan tiap orang Rp10.000.",
  "Transfer antar bank hanya bisa dilakukan pada hari kerja, pukul 08:00–17:00, dengan biaya berbeda per bank.",
  "Form nilai hanya bisa diisi oleh dosen pada semester berjalan dan jika mahasiswa terdaftar di kelas tersebut.",
  "Kuis online dengan timer otomatis, siswa tidak bisa menjawab soal setelah waktu habis.",
  "Sistem presensi otomatis gagal jika jam check-in lebih dari 10 menit dari jadwal kelas.",
  "Fitur upload tugas: maksimal 5 MB, format hanya .pdf atau .zip, hanya bisa diunggah 1 kali.",
  "Mahasiswa hanya bisa mengisi KRS jika total SKS semester sebelumnya ≥ 18 dan tidak ada nilai E.",
  "Booking tiket kereta: tidak bisa memesan lebih dari 4 penumpang dalam satu transaksi.",
  "Sistem parkir cerdas: kendaraan hanya bisa keluar jika RFID ditemukan dan saldo cukup.",
  "Pemilihan kursi bioskop hanya tersedia jika status kursi “available” saat tombol diklik.",
  "Sistem ride-sharing: pengguna bisa memilih driver hanya dalam radius 2 km dan rating ≥ 4.5.",
  "Booking hotel: check-in minimal 1 hari setelah tanggal booking, maksimal 30 hari ke depan.",
  "Aplikasi konversi mata uang: harus bisa mendeteksi mata uang invalid dan tidak menampilkan kurs palsu.",
  "To-do list: item yang sudah dicentang tidak bisa dihapus sebelum dikonfirmasi dua kali.",
  "Kalender digital: tidak bisa menambahkan event di masa lalu, kecuali untuk catatan retrospektif.",
  "Sistem alarm: pengguna tidak boleh membuat dua alarm dengan waktu sama, tapi label berbeda.",
  "Fitur pencarian produk: harus mengabaikan kapitalisasi, simbol, dan typo 1 huruf.",
];

export default features;
